// Generated by CoffeeScript 1.9.3
(function() {
  define(["text!sc/widget/index.html", "css!sc/widget/widget.css"], function(widgetHTML) {
    console.log("demo01 is loading! and widgetHTML is " + widgetHTML);
    $.ajax({
      type: "get",
      async: false,
      url: "http://localhost:18080/api/jsonp/jsonp_test?code=CA1998",
      dataType: "jsonp",
      jsonp: "callback",
      jsonpCallback: "callback",
      success: function(json) {
        return alert('����ѯ��������Ϣ��Ʊ�ۣ� ' + json.key1 + ' Ԫ����Ʊ�� ' + json.key2 + ' �š�');
      },
      error: function() {}
    });
    $.getScript('http://pv.sohu.com/cityjson', function() {
      var result;
      result = returnCitySN;
      return console.log(result);
    });
    $.getScript('http://localhost:18080/api/jsonp/jsonp_test?code=CA1998', function() {
      var result;
      result = sfun;
      return result();
    });
  });

}).call(this);

//# sourceMappingURL=demo01.js.map
