// Generated by CoffeeScript 1.9.3
(function() {
  var slice = [].slice;

  String.prototype.format = function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return this.replace(/\{(\d+)}/g, function(g0, g1) {
      return args[+g1];
    });
  };

  require.config({
    baseUrl: "http://localhost:10089/",
    urlArgs: {
      "Scripts/*": "v=" + (new Date - 0)
    },
    paths: {
      "lib": "libs",
      "sc": "Scripts"
    }
  });

  require(["lib/jquery/jquery-1.10.2", "lib/underscore/underscore"], function() {
    require(["sc/demo/demo02"], function() {
      return console.log("demo02 is loaded");
    });
    console.log("jquery underscore is loaded");
    console.log($(".mart6").html());
  });

}).call(this);

//# sourceMappingURL=main.js.map
